---

- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: true

- name: Configure HAProxy Load-Balancer
  hosts: HAproxy
  become: yes
  tasks:

    - name: Install HAProxy_
      apt:
        name: haproxy
        state: present
        update_cache: true
      

    - name: Gather server IP addresses
      setup:
        filter: ansible_default_ipv4.address     
         
    
    - name: Copy HAProxy configuration file
      template:
        src: haproxy.cfg.j2
        dest: "/etc/haproxy/haproxy.cfg"
      notify:
        - restart haproxy

  handlers:

    - name: Restart HAProxy
      service:
       name: haproxy
       state: restarted

- hosts: webservers
  become: yes
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
    
    - name: Install Flask
      pip:
        executable: pip3
        name: flask
        state: latest
    - name: Install Gunicorn
      pip:
        executable: pip3
        name: gunicorn
        state: latest

    - name: Create new directory
      file:
              path: "/home/flask-app/"
              state: directory
    - name: Copy Flask application to webservers
      template:
        src: "application2.py"
        dest: "/home/flask-app/app.py"


    - name: Start Flask application
      shell: |
        cd /home/flask-app/
        gunicorn --bind 0.0.0.0:80 app:app&
